### ISSUE TITLE
Typos from The Origins III: JavaScript

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#19]
Hello team,

Please find below a list of typos from The Origins III: JavaScript lessons.

### 01. Setting Up
- Replace 'was' with 'were', see picture typo001.png. 👇
![typo001](https://github.com/codedex-io/javascript-101/assets/48260426/fb7fd3de-8e8d-4097-969a-28021a3088fc)

- Replace 'on' with 'to', see picture typo010.png. 👇
![typo010](https://github.com/codedex-io/javascript-101/assets/48260426/3eb83864-2811-40fc-9de5-38c86d60aad5)

- Replace 'gets' with 'get'. see picture typo011.png. 👇
![typo011](https://github.com/codedex-io/javascript-101/assets/48260426/6f0544a7-335a-4c2c-a864-11cd1ee424b3)

**Comment by sonnynomnom** [comment]
Only the last bullet point is correct i think! Very nice work nevertheless! +2 points!
