### ISSUE TITLE
fix: variable in 16-air-quality-index.js

### ISSUE THREAD

**Issue by beingsie** [codedex-io/javascript-101#26]
# Issue description:
- Variable in `16-air-quality-index.js` is `api`. The correct variable should be `aqi`.

## Testing
- Upon testing in console the following error appears:
`VM125:3 Uncaught ReferenceError: aqi is not defined
    at <anonymous>:3:1`

## Screenshot of error on [Codédex.io](https://www.codedex.io/javascript/16-air-quality-index) console:
<img width="719" alt="image" src="https://github.com/codedex-io/javascript-101/assets/140430987/f14d9d88-ef90-43bf-9137-7d09a4b7c4b1">

**Comment by sonnynomnom** [comment]
completed and closed! +4!
