### ISSUE TITLE
Missing directory 40-the-dom in codedex-io/javascript-101

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#31]
Hello team,

There is a solution missing in the directory tree between 39-green-light-go and 41-hotline-bling. I seems that the solution of the JavaScript lesson 40. The DOM is missing.

See picture below for more context. 👇
![Screenshot_2023-10-28_09-21-36](https://github.com/codedex-io/javascript-101/assets/48260426/11a29ef6-a4ad-4aa3-aa71-2d28f64f5201)

**Comment by sonnynomnom** [comment]
I'm not going to deduct points for this one, but 40 doesn't have Instructions:

https://www.codedex.io/javascript/40-the-dom
