### ISSUE TITLE
Typo in JavaScript lesson 07. Data Types

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#32]
Hello team,

I would like to report a typo in this [lesson](https://www.codedex.io/javascript/07-data-types).

The string 'include', should be replaced with 'including'.

Please see the attached picture for more context. 👇
![Screenshot_2023-10-28_10-20-49](https://github.com/codedex-io/javascript-101/assets/48260426/33fd867b-63ca-49b5-ae30-a10f55c0d578)

**Comment by sonnynomnom** [comment]
Resolved! +4
