### ISSUE TITLE
Typo in JavaScript lesson 09. BMI

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#33]
Hello team,

I would like to report a typo in this [lesson](https://www.codedex.io/javascript/09-bmi).

The string 'subtraciton' should be replaced with 'subtraction'.

Please see the attached picture for more context.  👇
![Screenshot_2023-10-28_10-22-37](https://github.com/codedex-io/javascript-101/assets/48260426/009ce388-581f-4009-a1fb-d018eeaefb5d)

**Comment by sonnynomnom** [comment]
Resolved and +2'ed! Made the fix here:

https://github.com/codedex-io/curriculum/commit/a73dda172cf8c76860cc4b96ae168c8ed5620996
