### ISSUE TITLE
Typo in JavaScript lesson 12. Good Morning

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#34]
Hello team,

I would like to report a typo in this [lesson](https://www.codedex.io/javascript/12-good-morning).

The string 'messsage' should be replaced with 'message'.

Please see the attached picture for more context. 👇
![Screenshot_2023-10-28_10-37-23](https://github.com/codedex-io/javascript-101/assets/48260426/552b980d-feb4-4d7d-a71a-c9d7d393f072)

**Comment by sonnynomnom** [comment]
+2! Made the fix: https://github.com/codedex-io/curriculum/commit/2b4660ad55c26ba2a2801b4fd7e346c95c4befaa
