### ISSUE TITLE
Instructions of class 32. Clout with misinformation

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/javascript-101#45]
Hello team,

The last line of the instructions from this [lesson](https://www.codedex.io/javascript/32-clout), says that there are three functions to be ran.
However, the task is about creating two functions, as shown in the solution of that lesson.

Please see the attached picture for more context.
![Screenshot_2024-01-24_22-30-23](https://github.com/codedex-io/javascript-101/assets/48260426/222c9703-9a1c-485b-9ccb-23ca31509607)

**Comment by exrlla** [comment]
This fix has been implemented with the phrase
``` 
Lastly, call these functions on all three arrays and log the results to the Console! The output should look like this:
```
